// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package emergencia.entidad;

import emergencia.entidad.Direccion;

privileged aspect Albergue_Roo_JavaBean {
    
    public Direccion Albergue.getDireccion() {
        return this.direccion;
    }
    
    public void Albergue.setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    
}
