// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package emergencia.entidad;

import java.lang.String;

privileged aspect Direccion_Roo_JavaBean {
    
    public String Direccion.getCalle() {
        return this.calle;
    }
    
    public void Direccion.setCalle(String calle) {
        this.calle = calle;
    }
    
}
