// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package emergencia.entidad;

import emergencia.entidad.Usuario;

privileged aspect InstEncargada_Roo_JavaBean {
    
    public Usuario InstEncargada.getReponsable() {
        return this.reponsable;
    }
    
    public void InstEncargada.setReponsable(Usuario reponsable) {
        this.reponsable = reponsable;
    }
    
}
