// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package emergencia.entidad;

import java.lang.String;

privileged aspect Poblacion_Roo_ToString {
    
    public String Poblacion.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("IdPoblacion: ").append(getIdPoblacion());
        return sb.toString();
    }
    
}
