// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package emergencia.entidad;

import emergencia.entidad.Perfil;
import java.util.Set;

privileged aspect Usuario_Roo_JavaBean {
    
    public Set<Perfil> Usuario.getPerfiles() {
        return this.perfiles;
    }
    
    public void Usuario.setPerfiles(Set<Perfil> perfiles) {
        this.perfiles = perfiles;
    }
    
}
